global_options:
  dart_mappable_builder:
    options:
      caseStyle: snakeCase
      renameMethods:
        fromJson: deserialize
        toJson: serialize
        fromMap: fromJson
        toMap: toJson