name: rd_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  dart_mappable: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^3.2.1
  lints: ^2.0.0
  test: ^1.21.0
